---
title: "ggplot2, Chapter 3"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    theme: spacelab
    df_print: paged
---

```{r knitr-setup, include = FALSE}

library(knitr)

knitr::opts_chunk$set(eval = TRUE)

opts_chunk$set(fig.align = "center", fig.height = 4, fig.width = 8) # for html
opts_knit$set(progress = FALSE, verbose = TRUE)

```

## Toolbox

```{r, echo=FALSE}

require(data.table, quietly = TRUE, warn.conflicts = FALSE)
assignInNamespace("cedta.pkgEvalsUserCode", c(data.table:::cedta.pkgEvalsUserCode, "rtvs"), "data.table")

require(dplyr, quietly = TRUE, warn.conflicts = FALSE)
require(ggplot2, quietly = TRUE, warn.conflicts = FALSE)

require(directlabels, quietly = TRUE, warn.conflicts = FALSE)

mpg

```
### Section 3.2

#### Plot Types

### Exercises 3.2.1

> __Question 1__: 

> What geoms would you use to draw each of the following named plots?

> + `Scatterplot`
> + `Line Chart`
> + `Histogram`
> + `Bar chart`
> + `Pie Chart`

> __Answer__:

```{r ch_3.2.1_1}

df <- data.frame(x = c(3, 1, 5),
                 y = c(2, 4, 6),
                 label = c("a", "b", "c"))

p <- ggplot(df, aes(x, y, label = label)) +
    labs(x = NULL, y = NULL) + # Hide axis label
    theme(plot.title = element_text(size = 12))

p + geom_point() + ggtitle("point")
p + geom_text(label = "") + ggtitle("text")
p + geom_bar(stat = "identity") + ggtitle("bar")
p + geom_tile() + ggtitle("raster")

p + geom_line() + ggtitle("line")
p + geom_area() + ggtitle("area")
p + geom_path() + ggtitle("path")
p + geom_polygon() + ggtitle("polygon")

```

### Section 3.3

#### Text

```{r ch_3.3}

df <- data.frame(x = 1, y = 3:1, family = c("sans", "serif", "mono"))

ggplot(df, aes(x, y)) +
    geom_text(aes(label = family, family = family))

df <- data.frame(x = 1, y = 3:1, face = c("plain", "bold", "italic"))

ggplot(df, aes(x, y)) +
   geom_text(aes(label = face, fontface = face))

df <- data.frame(x = c(1, 1, 2, 2, 1.5),
                 y = c(1, 2, 1, 2, 1.5),
                 text = c(
                          "bottom-left", "bottom-right",
                          "top-left", "top-right", "center"))

ggplot(df, aes(x, y)) +
   geom_text(aes(label = text))

ggplot(df, aes(x, y)) +
   geom_text(aes(label = text, vjust = "inward", hjust = "inward"))

df <- data.frame(trt = c("a", "b", "c"), resp = c(1.2, 3.4, 2.5))

ggplot(df, aes(trt, resp)) +
   geom_point() +
   geom_text(aes(label = paste0("(", resp, ")")), nudge_y = -0.25)

ggplot(mpg, aes(displ, hwy)) +
   geom_text(aes(label = model)) +
   xlim(1, 8)

ggplot(mpg, aes(displ, hwy)) +
   geom_text(aes(label = model), check_overlap = T) +
   xlim(1, 8)

label <- data.frame(waiting = c(55, 80),
                    eruptions = c(2, 4.3),
                    label = c("peak one", "peak two"))

ggplot(faithfuld, aes(waiting, eruptions)) +
   geom_tile(aes(fill = density)) +
   geom_label(data = label, aes(label = label))

ggplot(mpg, aes(displ, hwy, colour = class)) +
   geom_point(show.legend = F) +
   directlabels::geom_dl(aes(label = class), method = "smart.grid")


```

### Section 3.4

#### Annotations


```{r ch_3.4}

ggplot(economics, aes(date, unemploy)) +
   geom_line()

presidential <- subset(presidential, start > economics$date[1])

ggplot(economics) +
    geom_rect(
       aes(xmin = start, xmax = end, fill = party),
       ymin = -Inf, ymax = Inf, alpha = 0.2,
       data = presidential
    ) +
    geom_vline(
        aes(xintercept = as.numeric(start)),
        data = presidential,
        colour = "grey50", alpha = 0.5
    ) +
    geom_text(
        aes(x = start, y = 2500, label = name),
        data = presidential,
        size = 3, vjust = 0, hjust = 0, nudge_x = 50
    ) +
    geom_line(aes(date, unemploy)) +
    scale_fill_manual(values = c("blue", "red"))

yrng <- range(economics$unemploy)
xrng <- range(economics$date)
caption <- paste(strwrap('Unemployment rates in the US have
    varied a lot over the years', 40), collapse = '\n')

ggplot(economics, aes(date, unemploy)) +
    geom_line() +
    geom_text(
        aes(x, y, label = caption),
        data = data.frame(x = xrng[1], y = yrng[2], caption = caption),
        hjust = 0, vjust = 1, size = 4
    )

ggplot(economics, aes(date, unemploy)) +
   geom_line() +
   annotate("text", x = xrng[1], y = yrng[2], label = caption,
            hjust = 0, vjust = 1, size = 4)

ggplot(diamonds, aes(log10(carat), log10(price))) +
   geom_bin2d() +
   facet_wrap(~cut, nrow = 1)

mod_coef <- coef(lm(log10(price) ~ log10(carat), data = diamonds))

ggplot(diamonds, aes(log10(carat), log10(price))) +
    geom_bin2d() +
    geom_abline(intercept = mod_coef[1], slope = mod_coef[2],
        colour = "white", size = 1) +
        facet_wrap(~cut, nrow = 1)

```

### Section 3.5

#### Collective Geoms

```{r ch_3.5}


```

